paths:
  images_root: "../../bdd100k_images_100k/100k"
  labels_root: "../../bdd100k_labels/100k"
  # 이 폴더 아래에 version01, version02 ... 식으로 계속 생성됨
  output_root: "../bdd_to_yolo/bdd100k_subset_filtered"

seed: 123

# ===== 여기서부터 조건별 설정 =====
conditions:
  # 1) day + clear
  - name: "day_clear"
    timeofday: "daytime"
    weather: "clear"
    scene: "any"       # scene은 신경 안 쓰면 "any"
    samples:
      train: 0    # 3800 + 800 + 800 = 5400
      val: 100
      test: 200

  # 2) day + rain
  - name: "day_rain"
    timeofday: "daytime"
    weather: "rainy"
    scene: "any"
    samples:
      train: 0     # 600 + 150 + 150 = 900
      val: 5000
      test: 200

  # 3) day + snow
  - name: "day_snow"
    timeofday: "daytime"
    weather: "snowy"
    scene: "any"
    samples:
      train: 0
      val: 100
      test: 200

  # 4) night + clear
  - name: "night_clear"
    timeofday: "night"
    weather: "clear"
    scene: "any"
    samples:
      train: 2000    # 6300 + 1350 + 1350 = 9000
      val: 100
      test: 200

  # 5) night + rain
  - name: "night_rain"
    timeofday: "night"
    weather: "rainy"
    scene: "any"
    samples:
      train: 0
      val: 100
      test: 200

  # 6) night + snow
  - name: "night_snow"
    timeofday: "night"
    weather: "snowy"
    scene: "any"
    samples:
      train: 0
      val: 100
      test: 200

